name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  build-orchestrator:
    runs-on:
      - machine
      - gpu=t4
      - tenancy=on_demand
      - cpu=4
      - ram=16
      - architecture=x64
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: crazy-max/ghaction-github-runtime@v3

      - name: Build orchestrator Docker image
        uses: docker/build-push-action@v6.11.0
        with:
          file: Dockerfile.orchestrator
          push: false
          build-args: |
            CONDA_PLUGINS_AUTO_ACCEPT_TOS=true
          cache-from: type=gha,scope=${{ github.ref_name }}-orchestrator
          cache-to:   type=gha,mode=max,ignore-error=true,scope=${{ github.ref_name }}-orchestrator

  build-image_server:
    runs-on:
      - machine
      - gpu=t4
      - tenancy=on_demand
      - cpu=4
      - ram=16
      - architecture=x64
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: crazy-max/ghaction-github-runtime@v3

      - name: Build image_server Docker image
        uses: docker/build-push-action@v6.11.0
        with:
          file: Dockerfile.image_server
          push: false
          build-args: |
            CONDA_PLUGINS_AUTO_ACCEPT_TOS=true
          cache-from: type=gha,scope=${{ github.ref_name }}-image_server
          cache-to:   type=gha,mode=max,ignore-error=true,scope=${{ github.ref_name }}-image_server
